myNextApplication:
  component: "@sls-next/serverless-component@1.19.0-alpha.45"
  inputs:
    env:
      API_TARGET: "<LAMBDA EXECUTE URL HERE>"
    build:
      env:
        API_TARGET: "<LAMBDA EXECUTE URL HERE>"