version: "3"

services: 

  nextjs-ui:
    build:
      context: ./docker/dev/nextjs
    ports:
      - 3000:3000
    depends_on: 
      - laravel-api
    container_name: nextjs-ui
    stdin_open: true
    volumes:
        - ./frontend:/app
    environment: 
      - API_TARGET=http://laravel-api:8000

  laravel-api:
    build:
      context: ./docker/dev/php
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - XDEBUG_CONFIG="remote_host=172.17.0.1"
      - PHP_IDE_CONFIG="serverName=laravel.local"
    user: 1000:82
    volumes:
        - ./backend:/app
        - ./docker/dev/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/dev/db/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  composer:
    build:
      context: ./docker/dev/php-composer
    environment:
      - XDEBUG_CONFIG="remote_host=172.17.0.1"
      - PHP_IDE_CONFIG="serverName=laravel.local"
    user: 1000:82
    volumes:
        - ./backend:/app